entries:
  - name: vast_standalone_storage_profiles
    selectors:
      solution: vast_data
      server_role: storage
      usage_type: default
    allowed_models:
      - Cisco UCS C225 M8
    profiles:
      default:
        policy_set:
          bios_policy: auto-vast-bios
          boot_policy: auto-vast-bootorder
          power_policy: auto-vast-power
          ipmi_policy: auto-vast-ipmi
          local_user_policy: auto-vast-localuser
          serial_over_lan_policy: auto-vast-sol
          virtual_kvm_policy: auto-vast-vkvm
          storage_policy: auto-vast-storage
        template:
          name: auto-vast-template
          target_platform: Standalone

  - name: oracle_rac_flexpod_compute_profiles
    selectors:
      solution: oracle_rac
      server_role: compute
      usage_type: controller
    allowed_models:
      - UCSX-210C-M7
      - UCSX-210C-M6
      - UCSB-B200-M5
    profiles:
      default:
        policy_set:
          bios_policy: flexpod-oracle-rac-compute-bios
          boot_policy: flexpod-oracle-rac-compute-boot
          lan_connectivity_policy: flexpod-oracle-rac-compute-lan
          san_connectivity_policy: flexpod-oracle-rac-compute-san

