layouts:
  - name: fi_default_uplink_layout
    selectors:
      model: UCS-FI-6536
    uplink_port_channels:
      - name: default-uplink-pc
        pc_id: 100
        member_ports:
          - "1/33"
          - "1/34"
        admin_speed: Auto
        fec: Auto
    server_ports:
      - port_id: "1/1"
        state: present
      - port_id: "1/2"
        state: present

